services:
  db:
    image: mysql:8
    container_name: zomzom_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zomzom}
      MYSQL_USER: ${MYSQL_USER:-zomzom}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zomzompass}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      # *** สำคัญ: override URL สำหรับ "ในคอนเทนเนอร์" ให้ใช้ host ชื่อ db:3306 ***
      DATABASE_URL: ${DATABASE_URL_DOCKER:-mysql://zomzom:zomzompass@db:3306/zomzom}
      HOST: 0.0.0.0
      PORT: ${PORT:-4000}
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./public:/app/public
    restart: unless-stopped

volumes:
  dbdata:
